os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -e .
  - pip install coverage
  - pip install codecov
script:
  - coverage run --source yasoo -m unittest discover tests
after_success:
  - codecov
