os: linux
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install -e .
  - pip install coverage
script:
  - coverage run --source yasoo -m unittest discover tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
